# Generated by Django 3.2.7 on 2021-09-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jok_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='photos/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='J_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bob_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='photos/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
