# Generated by Django 3.2.7 on 2021-09-06 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_bob_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bob_comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bob_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_comments', to='main.jok_post'),
        ),
        migrations.AlterField(
            model_name='jok_comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
