# Generated by Django 3.2.7 on 2021-09-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210907_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bob_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='B_comments', to='main.bob_post'),
        ),
    ]
